### ISSUE TITLE
Update to v3 version of client

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/DEMO-NewsPublications#8]
This repo still uses a very old version of the [weaviate python client](https://github.com/semi-technologies/DEMO-NewsPublications/blob/d3a900ed02cfd5077ae461550d9059960ff7882e/requirements.txt#L2). This makes it hard to work with this dataset locally when all other repos already use v3.x.y.

Would appreciate if this could get updated.

**Comment by bobvanluijt** [comment]
@michaverhagen – can somebody from your team pick up this request? I've also added it [here](https://github.com/semi-technologies/ops-project-management/issues/167)
